# Generated by Django 4.1.6 on 2023-02-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayAndHour',
            fields=[
                ('dah_id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.TextField()),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
            ],
            options={
                'db_table': 'day_and_hour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('poi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('average_visiting_time', models.IntegerField()),
            ],
            options={
                'db_table': 'poi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoiOpeningHour',
            fields=[
                ('poh_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'poi_opening_hour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('min_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('min_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('max_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('max_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialInteraction',
            fields=[
                ('si_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024)),
                ('source_type', models.TextField()),
            ],
            options={
                'db_table': 'social_interaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('sm_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024)),
                ('source_type', models.TextField()),
            ],
            options={
                'db_table': 'social_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.TextField(blank=True, null=True)),
                ('disability', models.IntegerField()),
            ],
            options={
                'db_table': 'user_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('ut_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_tag',
                'managed': False,
            },
        ),
    ]
