# Generated by Django 4.2.1 on 2023-06-14 15:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayAndHour',
            fields=[
                ('dah_id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(max_length=3)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'day_and_hour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('json', models.CharField(max_length=8192)),
                ('last_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('poi_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('average_visiting_time', models.IntegerField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField()),
                ('suitable_for_disabled', models.BooleanField()),
            ],
            options={
                'db_table': 'poi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoiOpeningHour',
            fields=[
                ('poi_opening_hour_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poi_opening_hour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('min_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('min_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('max_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('max_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialInteraction',
            fields=[
                ('si_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024)),
                ('source_type', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'social_interaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('sm_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024)),
                ('source_type', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'social_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('disability', models.IntegerField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('ut_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='images/')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('poi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='api.poi')),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
    ]
