# Generated by Django 4.1.7 on 2023-02-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('ut_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_tag',
                'managed': False,
            },
        ),
    ]
