# Generated by Django 4.1.7 on 2023-02-23 19:59

import api.utils.db_types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usertag'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', api.utils.db_types.GenderField()),
                ('disability', models.IntegerField()),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_account',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
