# Generated by Django 4.2.1 on 2023-06-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_pois'),
    ]

    operations = [
    ]
