# Generated by Django 4.2.1 on 2023-06-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_place_json'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='image',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='precompileditinerary',
            order_with_respect_to=None,
        ),
    ]
