# Generated by Django 4.1.7 on 2023-02-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_delete_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('it_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('ds_id', models.AutoField(primary_key=True, serialize=False)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.itinerary')),
                ('poi', models.ManyToManyField(to='api.poi')),
            ],
        ),
    ]
