# Generated by Django 4.2.1 on 2023-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_pois_image_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='poi',
            field=models.ManyToManyField(related_name='images', to='api.poi'),
        ),
    ]
