# Generated by Django 4.2.4 on 2024-03-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_precompileditinerarypoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precompileditinerary',
            name='poi',
        ),
        migrations.AddField(
            model_name='precompileditinerary',
            name='poi',
            field=models.ManyToManyField(related_name='poi', through='api.PrecompiledItinerary', to='api.poi'),
        ),
    ]
