# Generated by Django 4.1.7 on 2023-03-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_itinerary_user_delete_dailyschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoiOpeningHour',
            fields=[
                ('poh_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poi_opening_hour',
                'managed': False,
            },
        ),
    ]
