# Generated by Django 4.2.1 on 2023-06-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_image_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='poi',
            field=models.ManyToManyField(blank=True, related_name='images', to='api.poi'),
        ),
    ]
