# Generated by Django 4.2.1 on 2023-06-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_image_poi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecompiledItinerary',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, null=True)),
                ('poi', models.ManyToManyField(blank=True, to='api.poi')),
            ],
            options={
                'db_table': 'precompiled_itinerary',
                'managed': True,
            },
        ),
    ]
